name: Sailing On Dreams
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45895467116497457
title: Sailing On Dreams - Playing mind games with soul
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-140585-07
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7dcdf'
    - '#979ca0'
    - '#292e32'
    - '#6d7275'
    - '#4c5051'
  brandStrength: 0.25
  lightness: 0.03192770550958812
  saturation: 0.813403045758605
  rhythmicContrast: 0.6156287279445678
purpose: []
