name: Sailing On Dreams
favicon: null
layout_spectrum: 0.16813448956236243
typography_spectrum: 0.45895467116497457
title: Sailing On Dreams - Playing mind games with soul
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-140585-07
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#d7dcdf'
    - '#b1b8be'
    - '#8d9296'
    - '#606568'
  brandStrength: 0.9842990615870804
  lightness: 0.03192770550958812
  saturation: 0.813403045758605
  rhythmicContrast: 0.6156287279445678
purpose: []
